services:
  mockServer:
    image: mockserver/mockserver:5.15.0
    ports:
    - 1080:1080
    environment:
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
    volumes:
    - type: bind
      source: ./mockserver-config
      target: /config
